import { AuditReport, Category, Issue } from '../types/index.js';

const SEVERITY_EMOJI: Record<string, string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
  info: '⚪',
};

const CATEGORY_ICONS: Record<string, string> = {
  quality: '🔍',
  security: '🛡️',
  performance: '⚡',
  accessibility: '♿',
  testing: '🧪',
  architecture: '🏗️',
  dependencies: '📦',
};

export function generateMarkdownReport(report: AuditReport): string {
  const { score, summary, stack, results, ai, timestamp, path: auditPath } = report;
  const date = new Date(timestamp).toLocaleString();

  const lines: string[] = [];

  // ─── Header ──────────────────────────────────────────────────────────────
  lines.push(`# ⚡ CodeSetter Audit Report`);
  lines.push('');
  lines.push(`> Generated: ${date} · Path: \`${auditPath}\` · Stack: **${stack.primary}** ${stack.frameworks.join(', ')}`);
  lines.push('');

  // ─── Overall score badge ──────────────────────────────────────────────────
  lines.push(`## Overall Score: ${score.overall}/100 · Grade: **${score.grade}**`);
  lines.push('');

  // ─── Score table ──────────────────────────────────────────────────────────
  lines.push('| Category | Score | Grade | Issues | Critical |');
  lines.push('|----------|-------|-------|--------|----------|');
  for (const [cat, sub] of Object.entries(score.subScores)) {
    const icon = CATEGORY_ICONS[cat] ?? '';
    lines.push(
      `| ${icon} ${cat} | ${sub.score}/100 | ${sub.grade} | ${sub.issueCount} | ${sub.criticalCount} |`
    );
  }
  lines.push('');

  // ─── Summary ──────────────────────────────────────────────────────────────
  lines.push('## 📊 Issue Summary');
  lines.push('');
  lines.push(`| 🔴 Critical | 🟠 High | 🟡 Medium | 🔵 Low | ⚪ Info | 📁 Files |`);
  lines.push(`|------------|--------|----------|--------|---------|---------|`);
  lines.push(
    `| ${summary.criticalIssues} | ${summary.highIssues} | ${summary.mediumIssues} | ${summary.lowIssues} | ${summary.infoIssues} | ${summary.totalFiles} |`
  );
  lines.push('');

  // ─── AI Insights ─────────────────────────────────────────────────────────
  if (ai) {
    lines.push('## 🤖 AI Insights');
    lines.push('');
    lines.push(ai.overallSummary);
    lines.push('');
    lines.push('### Priority Actions');
    for (const action of ai.priorityActions) {
      lines.push(`- ${action}`);
    }
    lines.push('');
  }

  // ─── Issues by category ───────────────────────────────────────────────────
  for (const result of results) {
    if (result.issues.length === 0) continue;

    const icon = CATEGORY_ICONS[result.category] ?? '';
    lines.push(`## ${icon} ${capitalize(result.category)} Issues (Score: ${result.score}/100)`);
    lines.push('');

    const topIssues = result.issues
      .sort((a, b) => severityOrder(a) - severityOrder(b))
      .slice(0, 30);

    lines.push('| Severity | Issue | File | Line |');
    lines.push('|----------|-------|------|------|');

    for (const issue of topIssues) {
      const emoji = SEVERITY_EMOJI[issue.severity] ?? '⚪';
      const file = issue.location.file;
      const line = issue.location.line ? `:${issue.location.line}` : '';
      lines.push(
        `| ${emoji} ${issue.severity} | **${escapeMd(issue.title)}** — ${escapeMd(issue.description)} | \`${file}${line}\` | ${issue.location.line ?? '—'} |`
      );
    }

    if (result.issues.length > 30) {
      lines.push('');
      lines.push(`> Showing 30 of ${result.issues.length} issues.`);
    }

    // Show fixes for critical/high
    const critical = result.issues.filter(
      (i) => (i.severity === 'critical' || i.severity === 'high') && i.fix
    );

    if (critical.length > 0) {
      lines.push('');
      lines.push(`### Suggested Fixes`);
      for (const issue of critical.slice(0, 5)) {
        if (!issue.fix) continue;
        lines.push('');
        lines.push(`#### ${SEVERITY_EMOJI[issue.severity]} ${issue.title}`);
        lines.push(`> ${issue.location.file}${issue.location.line ? `:${issue.location.line}` : ''}`);
        lines.push('');
        lines.push(issue.fix.description);
        if (issue.fix.before && issue.fix.after) {
          lines.push('');
          lines.push('```diff');
          lines.push(`- ${issue.fix.before}`);
          lines.push(`+ ${issue.fix.after}`);
          lines.push('```');
        }
      }
    }

    lines.push('');
  }

  // ─── Footer ──────────────────────────────────────────────────────────────
  lines.push('---');
  lines.push(`*Generated by [CodeSetter](https://github.com/RudrakshRakeshZodage/CodeSetter) v${report.version} · Audit ID: \`${report.id}\`*`);

  return lines.join('\n');
}

function severityOrder(issue: Issue): number {
  const map: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
  return map[issue.severity] ?? 5;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function escapeMd(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
